mysite/assessment_app/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


urlpatterns = [
    path('', views.indexView, name='home'),
    path('logout/', views.logoutUser, name='logout'),
    path('login/', views.loginUser, name='login'),
    # path('signup/', views.signUp, name='signup'),
    # path('signup_request_list/', views.signupRequestList, name='signup_request_list'),
    # url(r'^signup_request/(?P<id>\d+)/(?P<act>\d+)/approval/$', views.signupRequestApproval, name='signuprequestapproval'),
    path('portco_list/', views.portcoList, name='portco_list'),
    path('portco/create/', views.portcoCreate, name='portco_create'),
    url(r'^portco/(?P<pk>\d+)/update/$', views.portcoUpdate, name='portco_update'),
    path('plant_list/', views.plantList, name='plant_list'),
    path('plant/create/', views.plantCreate, name='plant_create'),
    # path('ajax/load-region/', views.loadRegions, name='ajax_load_region'),
    path('ajax/load-state/', views.loadState, name='ajax_load_state'),
    url(r'^plant/(?P<pk>\d+)/update/$', views.plantUpdate, name='plant_update'),
    path('els_list/', views.elsList, name='els_list'),
    path('els/create/', views.elsCreate, name='els_create'),
    url(r'^els/(?P<pk>\d+)/update/$', views.elsUpdate, name='els_update'),
    path('ajax/load-plant/', views.loadPlant, name='ajax_load_plant'),
    path('area_list/', views.areaList, name='area_list'),
    path('area/create/', views.areaCreate, name='area_create'),
    url(r'^area/(?P<pk>\d+)/update/$', views.areaUpdate, name='area_update'),
    path('employee_list/', views.employeeList, name='employee_list'),
    path('employee/create/', views.employeeCreate, name='employee_create'),
    url(r'^employee/(?P<pk>\d+)/update/$', views.employeeUpdate, name='employee_update'),
    path('password/<int:id>/', views.resetPassword, name='reset_password'),
    url(r'^password/$', views.changePassword, name='change_password'),
    path('els_assessment/', views.elsRating, name='els_assessment'),
    url(r'^els_assessment/(?P<act>[\w\-]+)/(?P<assessment_date>[\w\-]+)/(?P<area>[\w\-]+)/display/$', views.elsRating, name='els_assessment_xyz'),
    path('els_assessment_submit/', views.elsRatingSubmmit, name='els_assessment_submit'),
    path('assessment/present', views.isElsAssessmentPresent, name='is_els_assessment_present'),
    path('area_assessment_submit/', views.elsAreaRatingSubmmit, name='els_area_assessment_submit'),
    path('els_area_redirection/', views.elsAreaRedirection, name='els_area_redirection'),
    path('lship_list/', views.lshipList, name='lship_list'),
    path('lship/create_category/', views.lshipCreateCategory, name='lship_create_category'),
    path('lship/create_level/', views.lshipCreateLevel, name='lship_create_level'),
    url(r'^lship/(?P<pk>\d+)/update/$', views.lshipUpdate, name='lship_update'),
    path('lship_list_category/', views.lshipListCategory, name='lship_list_category'),
    url(r'^lship/(?P<pk>\d+)/update_category/$', views.lshipUpdateCategory, name='lship_update_category'),
    path('lship_list_level/', views.lshipListLevel, name='lship_list_level'),
    url(r'^lship/(?P<pk>\d+)/update_level/$', views.lshipUpdateLevel, name='lship_update_level'),
    # url(r'^offline_section/(?P<act>[\w\-]+)/load/$', views.bulkUpload, name='bulk_upload'),
    url(r'^offline_section_type/(?P<act>[\w\-]+)/load/$', views.bulkUploadELS, name='bulk_upload_els'),
    path('offline_section/', views.bulkUpload, name='bulk_upload'),
    path('ajax/upload_validate/', views.uploadValidation, name='ajax_upload_validate'),
    path('lship_assessment/', views.lshipRating, name='lship_assessment'),
    url(r'^lship_assessment/(?P<act>[\w\-]+)/(?P<assessment_date>[\w\-]+)/display/$', views.lshipRating, name='lship_assessment_xyz'),
    path('lship_assessment_submit/', views.lshipRatingSubmmit, name='lship_assessment_submit'),
    path('lship_assessment/present/', views.isLshipAssessmentPresent, name='is_lship_assessment_present'),
    path('lship_redirection/', views.LshipRedirection, name='lship_redirection'),
    path('lship_analysis/',views.LshipCharts, name = 'lship_charts'),
    path('ajax/load-lship-doa/', views.loadlshipdoa, name='ajax_load_lship_doa'),
    path('training_content_list/', views.trainingContentList, name='training_content_list'),
    path('training/create/', views.trainingModuleCreate, name='training_create'),
    url(r'^download_training/(?P<id>[\w\-]+)content/$', views.downloadTrainingContent, name='download_training_content'),
    url(r'^training/(?P<pk>\d+)/update/$', views.trainingUpdate, name='training_update'),
    url(r'^download_evidence/(?P<assessment_date>[\w\-]+)/(?P<id>[\w\-]+)/(?P<act>[\w\-]+)/(?P<area_id>[\w\-]+)/content/$', views.downloadELSEVidence, name='download_evidence'),
    # url(r'^portco_plant/(?P<pk>\d+)$', views.portcoFundRedirect, name='portco_plant_redirect'),
    path('els_analysis/',views.ELSCharts, name = 'els_charts'),
    path('ajax/load-els-doa/', views.loadelsdoa, name='ajax_load_els_doa'),
    path('ajax/load-area-doa/', views.loadareadoa, name='ajax_load_area_doa'),
    path('baseline_analysis/',views.BaselineCharts, name = 'baseline_charts'),
    ######################### Yes/No Module ############
    # url(r'^els_assessment_yes_no/(?P<act>[\w\-]+)/(?P<assessment_date>[\w\-]+)/(?P<area>[\w\-]+)/display/$', views.elsRatingYesNO, name='els_assessment_yes_no_xyz'),
    # path('els/yes_no/create/', views.elsYesNoCreate, name='els_yes_no_create'),
    # url(r'^els/yes_no/(?P<pk>\d+)/update/$', views.elsYesNoUpdate, name='els_yes_no_update'),
    # path('els_yes_no_assessment_submit/', views.elsYesNoRatingSubmmit, name='els_yes_no_assessment_submit'),
    # path('yes_no/assessment/present', views.isYesNoElsAssessmentPresent, name='is_yes_no_els_assessment_present'),
    # path('yes_no_els_area_redirection/', views.yesNoElsAreaRedirection, name='yes_no_els_area_redirection'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('', include('assessment_app.urls')),
    path('admin/', admin.site.urls),
]

mysite/assessment_app/models.py
from django.db import models
from django.contrib.auth.models import User
import os
import json
from uuid import uuid4
from datetime import datetime, date
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# from .models import Role
# from audit_log.models import AuthStampedModel
# from audit_log.models.fields import CreatingUserField, CreatingSessionKeyField
# Create your models here.
# from django.db import models

# Create your models here.
# class Role(models.Model):
#     role_type = models.CharField(unique=True, max_length=100)

User.__str__ = lambda user: user.get_full_name()


class GlobalRegionMaster(models.Model):
    objects = models.Manager()
    region = models.CharField(max_length=500)

    def __str__(self):
        return self.region


class RegionCountryMapping(models.Model):
    objects = models.Manager()
    country = models.CharField(max_length=500)
    iso = models.CharField(max_length=10)
    region = models.ForeignKey(GlobalRegionMaster, related_name='region_global_category', on_delete=models.CASCADE)

    def __str__(self):
        return self.country


class CountryStateMapping(models.Model):
    objects = models.Manager()
    country = models.ForeignKey(RegionCountryMapping, related_name='country_mapping_category', on_delete=models.CASCADE)
    region = models.ForeignKey(GlobalRegionMaster, related_name='region_mapping_category', on_delete=models.CASCADE)
    state = models.CharField(max_length=500)

    def __str__(self):
        return self.state


class PorfolioCompanyMaster(models.Model):
    status = (
        (True, 'Inactive'),
        (False, 'Active')
    )

    aquired = (
        (True, 'Aquired'),
        (False, 'Due-Diligence')
    )

    objects = models.Manager()
    portco_name = models.CharField(unique=True,max_length=100)
    hq_region = models.ForeignKey(GlobalRegionMaster, related_name='portco_global_region', null=True, on_delete=models.CASCADE)
    hq_country = models.ForeignKey(RegionCountryMapping, related_name='portco_region_country', null=True, on_delete=models.CASCADE)
    hq_state = models.ForeignKey(CountryStateMapping, related_name='portco_country_state', null=True,
                                                   on_delete=models.CASCADE)
    industry = models.CharField(max_length=100)
    # industry = models.ForeignKey(IndustryMaster, related_name='client_industry', on_delete=models.CASCADE)
    primary_contact = models.CharField(max_length=100)
    primary_contact_mail = models.EmailField(max_length=100)
    description = models.CharField(max_length=500,blank=True, null=True)
    # logo = models.ImageField(upload_to='media/', default='default.png', blank=True)
    is_delete = models.BooleanField(choices=status, default=False)
    is_aquired = models.BooleanField(choices=aquired, default=False)
    added_by = models.ForeignKey(User, related_name='portco_added_by', null=True, on_delete=models.CASCADE)
    modified_by = models.ForeignKey(User, related_name='portco_modified_by', null=True, on_delete=models.CASCADE)
    added_on = models.DateTimeField(null=True)
    modified_on = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.portco_name


class UserDetails(models.Model):
    status = (
        (True, 'Inactive'),
        (False, 'Active')
    )
    is_orc_choice = (
        (u'', 'Employee Type'),
        (True, 'One Rock Capital Employee'),
        (False, 'Non One Rock Capital Employee')
    )

    objects = models.Manager()
    user = models.OneToOneField(User, related_name='user_id', null=True, on_delete=models.CASCADE)
    # tv_id = models.CharField(unique=True, max_length=50)
    # plant = models.ForeignKey(ManufacturingPlantMaster, max_length=10, on_delete=models.CASCADE)
    is_delete = models.BooleanField(choices=status, default=False)
    is_orc_employee = models.BooleanField(choices=is_orc_choice)
    is_confirm = models.BooleanField(default=False)
    designation_title = models.CharField(max_length=100)
    added_by = models.ForeignKey(User, related_name='user_detail_added_by', null=True, on_delete=models.CASCADE)
    modified_by = models.ForeignKey(User, related_name='user_detail_modified_by', null=True, on_delete=models.CASCADE)
    added_on = models.DateTimeField(default=datetime.now,blank=True)
    modified_on = models.DateTimeField(default=datetime.now, blank=True)
    portco = models.ForeignKey(PorfolioCompanyMaster, related_name='portco1', null=True, on_delete=models.CASCADE)


# class RegionMaster(models.Model):
#     objects = models.Manager()
#     country = models.CharField(max_length=500)
#     region = models.CharField(max_length=500)
#     state = models.CharField(max_length=500)
#     # added_by = models.ForeignKey(User, related_name='region_added_by', null=True, on_delete=models.CASCADE)
#     # modified_by = models.ForeignKey(User, related_name='region_modified_by', null=True, on_delete=models.CASCADE)
#     # added_on = models.DateTimeField(null=True)
#     # modified_on = models.DateTimeField(default=datetime.now, blank=True)


class PlantMaster(models.Model):
    class Meta:
        unique_together = (('plant_name', 'portco'),)

    status = (
        (True, 'Inactive'),
        (False, 'Active')
    )

    objects = models.Manager()
    plant_name = models.CharField(max_length=100)
    portco = models.ForeignKey(PorfolioCompanyMaster,related_name='portco', on_delete=models.CASCADE)
    region = models.ForeignKey(GlobalRegionMaster, related_name='plant_global_region', null=True, on_delete=models.CASCADE)
    country = models.ForeignKey(RegionCountryMapping, related_name='plant_region_country', null=True, on_delete=models.CASCADE)
    state = models.ForeignKey(CountryStateMapping, related_name='plant_country_state', null=True, on_delete=models.CASCADE)
    primary_contact = models.CharField(max_length=100)
    primary_contact_mail = models.EmailField(max_length=100)
    description = models.CharField(max_length=500, blank=True, null=True)
    is_delete = models.BooleanField(choices=status, default=False)
    added_by = models.ForeignKey(User, related_name='plant_added_by', null=True, on_delete=models.CASCADE)
    modified_by = models.ForeignKey(User, related_name='plant_modified_by', null=True, on_delete=models.CASCADE)
    added_on = models.DateTimeField(null=True)
    modified_on = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.plant_name


class FourPMaster(models.Model):
    objects = models.Manager()
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.description


class ELSCategoryMaster(models.Model):
    status = (
        (True, 'Inactive'),
        (False, 'Active')
    )

    objects = models.Manager()
    category_name = models.CharField(max_length=500)
    category_description = models.CharField(max_length=500)
    four_P_category = models.ForeignKey(FourPMaster, related_name='four_P_master',
                               on_delete=models.CASCADE)
    is_delete = models.BooleanField(choices=status, default=False)
    added_by = models.ForeignKey(User, related_name='els_category_added_by', null=True, on_delete=models.CASCADE)
    modified_by = models.ForeignKey(User, related_name='els_category_modified_by', null=True, on_delete=models.CASCADE)
    added_on = models.DateTimeField(null=True)
    modified_on = models.DateTimeField(default=datetime.now, blank=True)
    priority_rank = models.IntegerField(null=True)

    def __str__(self):
        return self.category_name


class ELSCategoryRatingMaster(models.Model):
    objects = models.Manager()
    els_category = models.ForeignKey(ELSCategoryMaster, related_name='els_category_master', null=True,
                                        on_delete=models.CASCADE)
    els_category_priority = models.ForeignKey(ELSCategoryMaster, related_name='els_category_priority', null=True, on_delete = models.CASCADE)
    score = models.IntegerField()
    description = models.CharField(max_length=2000)
    added_by = models.ForeignKey(User, related_name='els_rating_added_by', null=True, on_delete=models.CASCADE)
    modified_by = models.ForeignKey(User, related_name='els_rating_modified_by', null=True, on_delete=models.CASCADE)
    added_on = models.DateTimeField(null=True)
    modified_on = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.description


class AreaDetails(models.Model):
    status = (
        (True, 'Inactive'),
        (False, 'Active')
    )

    objects = models.Manager()
    area_name = models.CharField(max_length=500)
    plant = models.ForeignKey(PlantMaster, related_name='plant_area',
                                  on_delete=models.CASCADE)
    portco = models.ForeignKey(PorfolioCompanyMaster, related_name='portco_area',
                                  on_delete=models.CASCADE)
    description = models.CharField(max_length=2000)
    is_delete = models.BooleanField(choices=status, default=False)
    added_by = models.ForeignKey(User, related_name='area_added_by', null=True, on_delete=models.CASCADE)
    modified_by = models.ForeignKey(User, related_name='area_modified_by', null=True, on_delete=models.CASCADE)
    added_on = models.DateTimeField(null=True)
    modified_on = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.area_name


class ELSRatings(models.Model):
    status = (
        (True, 'Inactive'),
        (False, 'Active')
    )

    objects = models.Manager()
    score = models.ForeignKey(ELSCategoryRatingMaster, related_name='score_els', on_delete=models.CASCADE, null=True)
    score_y_n = models.IntegerField(null=True)
    plant = models.ForeignKey(PlantMaster, related_name='portco_els', on_delete=models.CASCADE)
    portco = models.ForeignKey(PorfolioCompanyMaster, related_name='portco_els', on_delete=models.CASCADE)

mysite/assessment_app/templates/assessment_section/area_section/area_create.html
{% extends 'index.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content%}
<style>
 .required-field::after {
    content: " *";
    color: red;
}
.no-wrap{
    white-space: nowrap;
}
#id_employee {
    height: 10rem;
    overflow-y: scroll;
    font-size: 0.98rem;
    padding: .5rem 1.06rem;
    border-color: #e5e9f2;
    border: 1px solid #ced4da;
}
[data-title]:hover:after {
    opacity: 1;
    transition: all 0.1s ease 0.5s;
    visibility: visible;
}
[data-title]:after {
    content: attr(data-title);
    background-color: White;
    color: #111;
    font-size: 120%;
    position: absolute;
    padding: 1px 5px 2px 5px;
    bottom: -1.6em;
    left: 100%;
    white-space: nowrap;
    box-shadow: 1px 1px 3px #222222;
    opacity: 0;
    border: 1px solid #111111;
    z-index: 99999;
    visibility: hidden;
}
[data-title] {
    position: relative;
}
dl {
    float: right;
    text-align: center;
    margin-top: 1rem;
}
dl dt{
    display: inline-block;
    width: 20px;
    height: 20px;
    vertical-align: middle;
}
dl dd{
    display: inline-block;
    margin: 0px 10px 0px 3px;
    padding-bottom: 0;
    vertical-align: middle;
}
dl dt.red{
    background: red;
}
dl dt.blue{
    background: #2fade7;
}

.hidden{
visibility:hidden;
overflow:hidden;
width:0px;
height:0px;
}
.hide{
display: none;
}
</style>
{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
{% endblock %}


<div class="card card-table-border-none" id="recent-orders" style="height: 100%;">
                    <div class="card-header justify-content-between">
                      <h2 style="font-size: 1.8rem;">Create Sub-Plants</h2>
                      {% if error %}
                         <script>
                              alert("{{error}}");
                          </script>
                      {% endif %}
                        <div class="btn-group form-inline" >
                              <div class="form-group">
                                  <lable style="color:black;font-size: 1.2rem;">Portfolio Co: </lable>&ensp;
                                  <div class="form-control" style="border-color: black;">
                                        {{ portco }}
                                  </div>&nbsp;&nbsp;&nbsp;&nbsp;
                                  <lable style="color:black;font-size: 1.2rem;">Plant: </lable>&ensp;
                                  <div class="form-control" style="border-color: black;">
                                      {{ plant }}
                                  </div>
                              </div>&emsp;
<!--                              <button class="btn btn-primary" type="submit" form="filter">Select</button>-->
							</div>

                    </div><br><br>
                    <div class="card-body pt-0 pb-5">
                        <div class="row">
                            <div class="col">
                                <form method="post" id="areaform" data-state-url="{% url 'ajax_load_state' %}" class="form-horizontal" action="{% url 'area_create' %}" enctype='multipart/form-data'>
                                {% csrf_token %}
                                <div class="form-group row form_row ">
                                    <label class="col-sm-auto col-form-label required-field">{{ form.area_name.label }}</label>
                                    <div class="col-sm-2">
                                       <input type="text" name="area_name_1" maxlength="500" class="form-control" required="">
                                        <input type="hidden" name="arealist" value="area_name_1">
                                    </div>
                                    <label class="col-sm-auto col-form-label required-field no-wrap">Description</label>
                                        <div class="col-sm-2">
                                            <input type="text" name="description_1" maxlength="2000" class="form-control" required="">
                                            <input type="hidden" name="descriptionlist" value="description_1">
                                        </div>

                                </div>

                                <div class="row">
                                    <div class="col-sm-auto">
                                    </div>
                                    <div class="col-sm-auto">
                                            <button class="btn btn-primary" style="float: right;" id="add_new" type="button"><i class="fa fa-plus" aria-hidden="true"></i>
                                                Add More</button>
                                    </div>
                                    <div class="col-sm-auto">
                                            <button class="btn btn-primary" style="float: right;" type="submit">Create Sub-Plant</button>
                                    </div>
                                    <div class="col-sm-auto">
                                            <input type="button" class="btn btn-danger" value="Back" onclick="history.back(-1)" />
                                    </div>
                                </div>
                        </form>
                        <br>

                            </div>
                        </div>


                    </div>

</div>
<div class="modal" tabindex="-1" id="mymodal" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

<script>
$( document ).ready(function() {
    $(".li-home-active").removeClass( "active" );
   $(".li-tr-active").addClass( "active" );
   $("#ui-elements").addClass( "show" );
});

$("#id_country").change(function () {
      var url = $("#plantform").attr("data-state-url");
      var country = $(this).val();
      $.ajax({
        url: url,
        data: {
          'country': country
        },
        success: function (data) {
          $("#id_state").html(data);
        }
      });

    });

$(document).ready(function() {
   var table =  $('.dataTable').DataTable({
        stripeClasses: [],
        scrollY:        '45vh',
        scrollCollapse: true
   });
  });


$( "#add_new" ).click(function() {
    var numItems = $('.form_row').length
    numItems = numItems + 1
    $( '<div class="form-group row form_row"><label class="col-sm-1 col-form-label required-field">{{ form.area_name.label }}</label><div class="col-sm-3"><input type="text" name="area_name_' + numItems + '" maxlength="500" class="form-control" required=""><input type="hidden" name="arealist" value="area_name_' + numItems + '"></div><label class="col-sm-1 col-form-label required-field no-wrap">Description</label><div class="col-sm-3"><input type="text" name="description_' + numItems + '" maxlength="2000" class="form-control" required=""><input type="hidden" name="descriptionlist" value="description_' + numItems + '"></div></div>' ).insertAfter( $(".form_row").last() );
});
</script>
{% endblock %}

mysite/assessment_app/templates/assessment_section/area_section/area_update.html
{% extends 'index.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content%}
<style>
 .required-field::after {
    content: " *";
    color: red;
}
.no-wrap{
    white-space: nowrap;
}
#id_employee {
    height: 10rem;
    overflow-y: scroll;
    font-size: 0.98rem;
    padding: .5rem 1.06rem;
    border-color: #e5e9f2;
    border: 1px solid #ced4da;
}
[data-title]:hover:after {
    opacity: 1;
    transition: all 0.1s ease 0.5s;
    visibility: visible;
}
[data-title]:after {
    content: attr(data-title);
    background-color: White;
    color: #111;
    font-size: 120%;
    position: absolute;
    padding: 1px 5px 2px 5px;
    bottom: -1.6em;
    left: 100%;
    white-space: nowrap;
    box-shadow: 1px 1px 3px #222222;
    opacity: 0;
    border: 1px solid #111111;
    z-index: 99999;
    visibility: hidden;
}
[data-title] {
    position: relative;
}
dl {
    float: right;
    text-align: center;
    margin-top: 1rem;
}
dl dt{
    display: inline-block;
    width: 20px;
    height: 20px;
    vertical-align: middle;
}
dl dd{
    display: inline-block;
    margin: 0px 10px 0px 3px;
    padding-bottom: 0;
    vertical-align: middle;
}
dl dt.red{
    background: red;
}
dl dt.blue{
    background: #2fade7;
}

.hidden{
visibility:hidden;
overflow:hidden;
width:0px;
height:0px;
}
.hide{
display: none;
}
</style>
{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
{% endblock %}


<div class="card card-table-border-none" id="recent-orders" style="height: 100%;">
                    <div class="card-header justify-content-between">
                      <h2 style="font-size: 1.8rem;">Update Area Of Opportunity</h2>
                      {% if error %}
                         <script>
                              alert("{{error}}");
                          </script>
                      {% endif %}
                        <div class="btn-group form-inline" >
                              <div class="form-group">
                                  <lable style="color:black;font-size: 1.2rem;">Portfolio Co: </lable>&ensp;
                                  <div class="form-control" style="border-color: black;">
                                        {{ portco }}
                                  </div>&nbsp;&nbsp;&nbsp;&nbsp;
                                  <lable style="color:black;font-size: 1.2rem;">Plant: </lable>&ensp;
                                  <div class="form-control" style="border-color: black;">
                                      {{ plant }}
                                  </div>
                              </div>&emsp;
<!--                              <button class="btn btn-primary" type="submit" form="filter">Select</button>-->
							</div>

                    </div><br><br>
                    <div class="card-body pt-0 pb-5">
                        <div class="row">
                            <div class="col">
                                <form method="post" id="areaform" data-state-url="{% url 'ajax_load_state' %}" class="form-horizontal" action="{% url 'area_update' form.instance.pk %}" enctype='multipart/form-data'>
                                {% csrf_token %}
                                    <div class="form-group row form_row">
                                    <label class="col-sm-auto col-form-label required-field">{{ form.area_name.label }}</label>
                                    <div class="col-sm-3">
                                       {% render_field form.area_name class="form-control" %}
                                    </div>
                                        </div>
                                    <div class="form-group row form_row">
                                    <label class="col-sm-auto col-form-label required-field no-wrap">Description</label>
                                        <div class="col-sm-3">
                                            {% render_field form.description class="form-control" %}
                                        </div>
<!--                                  </div>-->
<!--                                    <div class="form-group row form_row">-->
                                    <label class="col-sm-auto col-form-label required-field " >Status</label>
                                    <div class="col-sm-3">
                                       {% render_field form.is_delete class="form-control" %}
                                    </div>
                                  </div>

                                <div class="row">
                                    <div class="col-sm-7">
                                    </div>
                                    <div class="col-sm-2">
                                            <button class="btn btn-primary" type="submit" style="float: right;" onclick="return confirm('Are you sure?')">Update</button>
                                    </div>
                                    <div class="col-sm-2">
                                            <input type="button" class="btn btn-danger" value="Back" onclick="history.back(-1)" />
                                    </div>
                                </div>
                        </form>
                        <br>

                            </div>
                        </div>



                    </div>

</div>
<div class="modal" tabindex="-1" id="mymodal" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

<script>
$( document ).ready(function() {
    $(".li-home-active").removeClass( "active" );
   $(".li-tr-active").addClass( "active" );
   $("#ui-elements").addClass( "show" );
});

$("#id_country").change(function () {
      var url = $("#plantform").attr("data-state-url");
      var country = $(this).val();
      $.ajax({
        url: url,
        data: {
          'country': country
        },
        success: function (data) {
          $("#id_state").html(data);
        }
      });

    });
$(document).ready(function() {
   var table =  $('.dataTable').DataTable({
        stripeClasses: [],
        scrollY:        '45vh',
        scrollCollapse: true
   });
  });
  </script>
{% endblock %}